version: '3.8'
services:
  postgres:
    image: postgres:16.1
    ports:
      - "5433:5432"  # Map the default postgres port to the host
    environment:
      POSTGRES_DB: backend-template
      POSTGRES_USER: all
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data even when the container shuts down

volumes:
  postgres-data:  # Named volume for persisting data
